repos/CS Technical Assignment/force-app/main/default/objects/Visitor__c/Visitor__c.object-meta.xml
<CustomObject>
    <label>Visitor</label>
    <nameField>
        <label>Visitor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

repos/CS Technical Assignment/force-app/main/default/objects/Visitor__c/fields/Date_Of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Birth__c</fullName>
    <label>Date Of Birth</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

repos/CS Technical Assignment/force-app/main/default/objects/Visitor__c/fields/Visit_Count__c.field-meta.xml
<CustomField>
    <fullName>Visit_Count__c</fullName>
    <label>Visit Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

repos/CS Technical Assignment/force-app/main/default/classes/SearchController.cls
public with sharing class SearchController {
    @AuraEnabled
    public static string saveUserInformation(String IdNumber, String dateOfBirth, String gender, Boolean saCitizen){
        Integer firstVisitCount = 0;
        try {
            List<Visitor__c> visitor = [SELECT Id, Name, Visit_Count__c FROM Visitor__c WHERE Name =: IdNumber];

            if(!visitor.isEmpty()){
                visitor[0].Visit_Count__c++;

                try{
                    update visitor;
                    return 'Update Success';
                } catch(DMLException e){
                    return e.getMessage();
                }
            }else{
                Visitor__c newVisitor = new Visitor__c();  

                newVisitor.Name = IdNumber;
                newVisitor.Date_Of_Birth__c = dateOfBirth;
                newVisitor.Gender__c = gender;
                newVisitor.SA_Citizen__c = saCitizen;
                newVisitor.Visit_Count__c = firstVisitCount + 1;

                try{
                    insert newVisitor;
                    return 'Insert Success';                    
                } catch(DMLException e){
                    return e.getMessage();
                }
            }            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }    
    }
}